### ISSUE TITLE
Update rate of peripheral coverage site?

### ISSUE THREAD

**Issue by xd009642** [adamgreig/stm32-rs#16]
Just wondering for the sake of better focusing my efforts, how often is https://stm32.agg.io/rs/ updated and is an update triggered automatically or manually?

Might be worth if it's not automatic setting up travis to force an update on every merge into master.

**Comment by xd009642** [comment]
I know of people using github oauth tokens to push updates to github hosted pages for documentation etc. I can have a look to see if I can find any useful resources and maybe prototype how it works with travis on a test repo if you'd like. (Not tonight, but Friday or the weekend I can get to it).

**Comment by adamgreig** [comment]
Thanks for the offer! I've set that sort of thing up a bunch in the past so I should be OK to figure it out. I've manually updated them for now (currently uploading..).

**Comment by adamgreig** [comment]
The website is now updated every 15min with the latest git master. Ultimately github pages won't work as the html directory is >500MB after generation...
