### ISSUE TITLE
Use form to split device files into mutiple folder.

### ISSUE THREAD

**Issue by gbip** [adamgreig/stm32-rs#19]
I think it is a good idea to use form to split devices files (`stm32f429.rs`) into a folder with subfolder for each module.
I can implement it if you want to :smile:

**Comment by gbip** [comment]
Hey @adamgreig can you take a look at this :smile:
I am willing to implement it if you think that it can make documentation generation easier !

**Comment by adamgreig** [comment]
If you'd like to have a go I'm happy to review, I'm up for at least seeing what it looks like and happy to merge if it seems reasonable. If it makes documentation easier then even better!

I imagine we'd have a folder for each device, so like `stm32f4/src/stm32f405/` which contains the generated files, and then feature-gated modules in `lib.rs` as currently?

**Comment by adamgreig** [comment]
The support for svd2rust 0.13.1 means each device already gets its own folder, so hopefully running Form over it should be even easier now. I'll have a play with it this week.

**Comment by gbip** [comment]
I'll try to see how it plays out this week too.

**Comment by gbip** [comment]
So since I am not familiar at all with Makefiles, I didn't do anything except running form on a few `mod.rs` with success (by hand).

**Comment by adamgreig** [comment]
Closed by #29
