### ISSUE TITLE
USART1EN mixed up with USART3EN

### ISSUE THREAD

**Issue by bergus** [adamgreig/stm32-rs#34]
In the STM32L4x2.svd I found that `APB1ENR1` contains an `USART1EN` bit in position 18, which actually (according to the pdf docs) does enable the *third* USART and should thus be named `USART3EN`. (The first USART is enabled by the `USART1EN` bit in position 14 of `APB2ENR`, which is correct in the svd file).

I'm not sure of the correct approach to fix this, and haven't checked how many other SVD files do contain this mistake, so I'm not going to make a PR myself.

**Comment by adamgreig** [comment]
Wow, that's shocking. I should keep a rogue's gallery of these.

The issue is present in stm32l4x2.svd and stm32l4x1.svd. In both cases the fix is updating the one in APB1ENR1 to be USART3EN.
