### ISSUE TITLE
How to contribute to coverage?

### ISSUE THREAD

**Issue by MattCatz** [adamgreig/stm32-rs#51]
I am currently going through a university lab focusing on the [32L100CDISCOVERY](https://www.st.com/en/evaluation-tools/32l100cdiscovery.html). This board 'helps you to discover the features of the STM32L100 Value Line.' I would be more than happy to contribute to [coverage](https://stm32.agg.io/rs/STM32L100.html) but I do not know how to.

**Comment by adamgreig** [comment]
Given your recent successful PRs I guess you figured this out! It could perhaps be better documented...
