### ISSUE TITLE
STM32F4 family ETH_MACIIDR RM0090 discrepancy

### ISSUE THREAD

**Issue by therealprof** [adamgreig/stm32-rs#69]
peripherals/eth/eth_mac.yaml says:

```
  MACMIIDR:
    TD: [0, 0xFFFF]
```

However the RM0090 says the field is support to be called `MD`. I guess the reason it is called `TD` is that some other series (or special sibling) call it `TD` in the documentation but I'm wondering how we want to treat such discrepancies...

**Comment by adamgreig** [comment]
Another ST classic.

The SVD file ST provide for the F405 -- and F469, F429, F427, F407, F7x7, F7x9, F7x6, and F7x5 -- all call it TD. The SVD files for the F101, 103, 107, 215, and 217 all call it MD. All the RMs I checked call it MD instead.

I think the solution is to rename TD to MD in the relevant SVD files, and update the `eth_mac.yaml` to say MD as well.

**Comment by adamgreig** [comment]
```
$ rg -A8 MACMIIDR *.svd | rg TD
stm32f7x5.svd-              <name>TD</name>
stm32f7x6.svd-              <name>TD</name>
stm32f7x9.svd-              <name>TD</name>
stm32f7x7.svd-              <name>TD</name>
stm32f405.svd-              <name>TD</name>
stm32f407.svd-              <name>TD</name>
stm32f427.svd-              <name>TD</name>
stm32f429.svd-              <name>TD</name>
stm32f469.svd-              <name>TD</name>
$ rg -A8 MACMIIDR *.svd | rg MD
stm32f101.svd-              <name>MD</name>
stm32f103.svd-              <name>MD</name>
stm32f107.svd-              <name>MD</name>
stm32f215.svd-              <name>MD</name>
stm32f217.svd-              <name>MD</name>
```

**Comment by therealprof** [comment]
Why do the F101/F103/F215/F405 have descriptions for ethernet at all?

**Comment by adamgreig** [comment]
> Another ST classic.

**Comment by adamgreig** [comment]
At the moment we can't remove or delete peripherals/registers/fields from the SVD in a yaml file, but it's becoming increasingly clear we need to for things like this. I think the more pressing thing would be changing TD to MD and releasing 0.3.2 really soon (it's technically a breaking change but if 0.3.1 has been out for an hour I wouldn't feel too terrible pushing it into that...).

Removing the ethernet peripheral from F101 F103 F215 F405 is slightly lower priority I think, but should still happen.

**Comment by therealprof** [comment]
Oh, don't rush it. There's more coming. ;)

**Comment by adamgreig** [comment]
:+1:
