### ISSUE TITLE
How to access interrupt!() macro?

### ISSUE THREAD

**Issue by therealprof** [adamgreig/stm32-rs#74]
I've tried various things things now but no matter how hard I try I can't get the `interrupt!()` macro into scope. Is there any example how to achieve that or is this something that hasn't been tested yet?

I'm in the progress of moving my `stm32f042-hal` crate from my custom peripheral registers crate over to `stm32f0` with the features `["rt", "stm32f0x2"]` and everything is working fine except for the interrupts macro...

```
error: cannot find macro `interrupt!` in this scope
  --> examples/led_hal_button_irq.rs:87:1
   |
87 | interrupt!(EXTI0_1, button_press);
   | ^^^^^^^^^
```

**Comment by adamgreig** [comment]
Have you got the `rt` feature enabled? It's required to get the interrupt macro (as per [the svd2rust docs](https://docs.rs/svd2rust/0.12.0/svd2rust/#the-rt-feature)) and it Just Works for me when I have that enabled (with `#[macro_use]` on the `extern crate stm32f3` as usual).

**Comment by adamgreig** [comment]
Sorry, I just realised you obviously do have the `rt` feature since you say so in your post. Are you using `#[macro_use]`?

**Comment by therealprof** [comment]
So much to my surprise to macro ends up in the toplevel crate, not the series specific module. To use it throughout the HAL crate I'm now successfully using
```
pub extern crate stm32f0;
pub use stm32f0::interrupt;
pub use stm32f0::stm32f0x2 as stm32;
```
