### ISSUE TITLE
Unable to modify svd cpu node

### ISSUE THREAD

**Issue by tones111** [adamgreig/stm32-rs#9]
Looking through svdpatch.py it doesn't appear that it's able to handle modifcations to cpu node children.

For example, stm32f303.svd contains

 `<cpu>... <nvicPrioBits>3</nvicPrioBits>...</cpu>`

However, the reference manual (RM0316, Section 14.1.1) states "4 bits of interrupt priority are used"

**Comment by adamgreig** [comment]
You're right, at the moment it doesn't have any way to modify things outside of the peripheral blocks, but clearly there are bugs everywhere that will need patching! I'll think about how to address this.

**Comment by tones111** [comment]
It would seem to me that there are several groups that would be interested in maintaining changes to svd files.  Especially if svds are being used to generate for other architectues.  There's no reason we should all be doing the same task differently.

@japaric
It might make more sense to discuss tooling at the broader embedded rust level.  If we could agree on the config file format then only one tool would need to be developed for the entire ecosystem.

The downside of the approach here is that it requies external python dependencies which doesn't play well with cargo builds.  Moving the implementation into a rust library would work really well for build.rs usage.

**Comment by therealprof** [comment]
@adamgreig Any news about this? I'd need to add missing interrupts to `stm32f7x7`...

**Comment by adamgreig** [comment]
@therealprof that's a similar but distinct problem around editing/adding `<interrupt>` nodes inside a `<peripheral>`, right?

**Comment by therealprof** [comment]
@adamgreig Yes, that's right.

**Comment by adamgreig** [comment]
I've roughed out an extension to the DSL to permit editing the cpu node and interrupts etc, shown [here](https://github.com/adamgreig/stm32-rs/compare/extend-dsl). It's back-compat with all the existing stuff but should make it easy to change anything else in the SVD. I'll hopefully get it implemented tomorrow evening; any thoughts?

**Comment by adamgreig** [comment]
@therealprof could you open another issue (or PR) for the missing interrupts, or point me to which ones they are? It should now be possible to add them.

**Comment by therealprof** [comment]
Sure, it's a bit tricky to figure out which ones are missing but I've already identified a few.
