### ISSUE TITLE
Consider adding a CHANGELOG

### ISSUE THREAD

**Issue by nickray** [adamgreig/stm32-rs#93]
It would be great to easily see what got fixed between, e.g., 0.3.2 and 0.4.0 in human-readable form.
Reference: https://keepachangelog.com

**Comment by adamgreig** [comment]
There is already a changelog: https://github.com/adamgreig/stm32-rs/blob/master/CHANGELOG.md

**Comment by nickray** [comment]
Oops, sorry! Not sure how I missed it :(
